name: Python Pull Request Workflow

on: [pull_request]

jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
          POSTGRES_DB: bookstore_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.13

      - name: Install poetry
        run: |
          pip install -U pip
          pip install poetry
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Install dependencies
        shell: bash
        run: python -m poetry install

      - name: Test
        env:
          SECRET_KEY: foo 
          SQL_ENGINE: django.db.backends.postgresql
          SQL_DATABASE: bookstore_db
          SQL_USER: dev
          SQL_PASSWORD: dev
          SQL_HOST: localhost
          SQL_PORT: 5432
        run: |
          poetry run python manage.py test

      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}